#@ load("@ytt:data", "data")
#@ load("@ytt:template", "template")

#@ def job_names(releases=[]):
#@ for/end release in releases:
- #@ "update" + release.name
#@ end

#@ def resources(releases=[], type=""):
#@ for/end release in releases:
- name: #@ release.name + "-release"
  type: #@ type
  source:
  #@ if type=="bosh-io-release":
    repository: #@ release.repository
  #@ elif type=="gcs-resource":
    bucket: cf-deployment-compiled-releases
    json_key: ((concourse_gcp_service_account_json))
    regexp: #@ release.name + "-[^-]+-ubuntu-trusty-[^-]+-(\d+)-(\d+)-(\d+).*\.tgz"
  #@ elif type=="bosh-io-stemcell":
    name: #@ "bosh-google-kvm-" + release.name + "-go_agent"
  #@ end
#@ end

#@ def upload_stemcell(releases=[]):
- name: upload-stemcell
  public: true
  serial_groups:
  - stemcell
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: relint-envs
    - get: cf-deployment-develop
    - get: cf-deployment-concourse-tasks
  #@ for/end release in releases:
    - get: #@ release.name + "-release"
      params:
        tarball: false
      trigger: true
    - get: stemcell
      params:
        tarball: false
  - task: upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcells/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: cf-deployment-develop
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      INFRASTRUCTURE: google
#@ end

#@ def update_release_jobs(releases=[], upload_stemcell=False):
#@ for/end release in releases:
- name: #@ "update-" + release.name
  #@ if upload_stemcell:
  serial: true
  #@ else:
  serial_groups:
  - stemcell
  - #@ "update-" + release.name
  #@ end
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-develop
    - get: cf-deployment-concourse-tasks
    - get: relint-envs
    - get: #@ release.name + "-release"
      trigger: true
      params:
        tarball: false
      passed: [ upload-stemcell ]
    - get: stemcell
      params:
        tarball: false
      passed:
      #@ if upload_stemcell:
      - update-stemcell-and-recompile-releases
      #@ else:
      - upload-stemcell
      #@ end
  - task: #@ "update-release-" + release.name
    file: runtime-ci/tasks/update-single-manifest-release/task.yml
    input_mapping:
      release: #@ release.name + "-release"
      deployment-configuration: cf-deployment-develop
    params:
      RELEASE_NAME: #@ release.name
  #@ if/end upload_stemcell:
  - task: bosh-upload-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcells/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: cf-deployment-develop
      ops-files: cf-deployment-develop
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      INFRASTRUCTURE: google
      OPS_FILES: |
        operations/windows2012R2-cell.yml
        operations/windows2016-cell.yml
        operations/windows1803-cell.yml
        operations/windows2019-cell.yml
  #@ if release.name.count("buildpack")==0:
  - task: bosh-dry-run
    file: runtime-ci/tasks/bosh-dry-run-with-ops/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: updated-deployment-manifest
      ops-files: cf-deployment-develop
      vars-files: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      DEPLOYMENT_NAME_SUFFIX: #@ release.name
      SYSTEM_DOMAIN: greengrass.cf-app.com
      #@ if/end hasattr(release, "varsFiles"):
      VARS_FILES: #@ release.varsFiles
  - task: bosh-delete-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      DEPLOYMENT_NAME: #@ "cf-dry-run-" + release.name
  #@ end
  - task: compile-release
    file: runtime-ci/tasks/compile-release-from-manifest/task.yml
    input_mapping:
      bbl-state: relint-envs
      manifest: updated-deployment-manifest
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      RELEASE_NAME: #@ release.name
  - task: #@ "update-additional-ops-files-" + release.name
    file: runtime-ci/tasks/update-single-opsfile-release/task.yml
    input_mapping:
      release: #@ release.name + "-release"
      original-ops-file: cf-deployment-develop
    params:
      RELEASE_NAME: #@ release.name
  - task: update-compiled-release-ops
    file: runtime-ci/tasks/update-single-compiled-release/task.yml
    input_mapping:
      original-compiled-releases-ops-file: cf-deployment-develop
      release: #@ release.name + "-release"
      compiled-release-tarball: exported-release
      current-commit-message: commit-message
    params:
      RELEASE_NAME: #@ release.name
      ORIGINAL_OPS_FILE_PATH: operations/use-compiled-releases.yml
      UPDATED_OPS_FILE_PATH: operations/use-compiled-releases.yml
  - task: combine-inputs
    file: runtime-ci/tasks/combine-inputs/task.yml
    input_mapping:
      first-input: updated-compiled-releases-ops-file
      second-input: updated-ops-file
  - put: #@ release.name + "-release-gcs"
    params:
      file: exported-release/*.tgz
      predefined_acl: publicRead
  - task: commit-generated-manifest-and-ops
    file: runtime-ci/tasks/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      ops-file: combined-inputs
      manifest: updated-deployment-manifest
    params:
      MANIFEST_NAME: cf-deployment.yml
      MANIFEST_DESTINATION: cf-deployment.yml
      COMMIT_ALL_OPS_FILES: true
  - put: cf-deployment-develop
    params:
      rebase: true
      repository: updated-repo
#@ end

#@ def update_stemcell_jobs(stemcells=[]):
#@ for/end stemcell in stemcells:
- name: #@ "update-" + stemcell.name + "-stemcell"
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: cf-deployment-develop
    - get: #@ stemcell.name + "-stemcell"
      trigger: true
      params:
        tarball: false
  - task: update-windows-stemcell-ops
    file: runtime-ci/tasks/update-windows-stemcell-ops/task.yml
    input_mapping:
      ops-files: cf-deployment-develop
      windows-stemcell: #@ stemcell.name + "-stemcell"
    params:
      ORIGINAL_WINDOWS_OPS_FILE_PATH: #@ "{}/{}".format(stemcell.opsFileDir, stemcell.opsFile)
      UPDATED_WINDOWS_OPS_FILE_PATH: #@ stemcell.opsFile
  - task: commit-generated-manifest-and-ops
    file: runtime-ci/tasks/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      ops-file: updated-stemcell-ops-file
      manifest: cf-deployment-develop
    params:
      OPS_FILE_NAME: #@ stemcell.opsFile
      OPS_FILE_DESTINATION: #@ "{}/{}".format(stemcell.opsFileDir, stemcell.opsFile)
  - put: cf-deployment-develop
    params:
      rebase: true
      repository: updated-repo
#@ end

---
groups:
- name: update-base-stemcells-and-releases
  jobs:
  - update-stemcell-and-recompile-releases
  - upload-stemcell
  - #@ template.replace(job_names(data.values.baseReleases))
- name: update-ops-releases
  jobs:
  - #@ template.replace(job_names(data.values.opsReleases))
- name: update-windows-stemcells-and-releases
  jobs:
  - #@ template.replace(job_names(data.values.windowsVersSupported))
  - update-windows-2016-offline-releases

- name: infrastructure
  jobs:
  - setup-infrastructure-compilation
  - destroy-infrastructure-compilation
  - run-bosh-cleanup-compilation

resource_types:
- name: gcs-resource
  type: docker-image
  source:
    repository: frodenas/gcs-resource

resources:
- name: cf-deployment-develop
  type: git
  source:
    branch: develop
    uri: git@github.com:cloudfoundry/cf-deployment.git
    private_key: ((cf_deployment_readwrite_deploy_key.private_key))
    ignore_paths:
    - ci/**
    - .envrc
- name: cf-deployment-concourse-tasks
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/cf-deployment-concourse-tasks.git
- name: relint-envs
  type: git
  source:
    branch: master
    uri: git@github.com:cloudfoundry/relint-envs.git
    private_key: ((hagrid_env_readwrite_deploy_key.private_key))
- name: runtime-ci
  type: git
  source:
    branch: master
    uri: https://github.com/cloudfoundry/runtime-ci.git
- name: stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-xenial-go_agent
- name: windows2016fs-offline-release
  type: github-release
  source:
    owner: cloudfoundry-incubator
    repository: windows2016fs-release
    access_token: ((release_integration_download_bot_access_token))
- #@ template.replace(resources(data.values.baseReleases, "bosh-io-release"))
- #@ template.replace(resources(data.values.opsReleases, "bosh-io-release"))
- #@ template.replace(resources(data.values.baseReleases, "gcs-resource"))
- #@ template.replace(resources(data.values.windowsVersSupported, "bosh-io-stemcell"))
- name: daily
  type: time
  source:
    start: 3:00 -0700
    stop: 3:30 -0700
    interval: 24h

jobs:
- #@ template.replace(upload_stemcell(data.values.baseReleases))
- #@ template.replace(update_release_jobs(data.values.baseReleases))
- #@ template.replace(update_release_jobs(data.values.opsReleases, True))
- #@ template.replace(update_stemcell_jobs(data.values.windowsVersSupported))

- name: update-stemcell-and-recompile-releases
  public: true
  serial_groups:
  - stemcell
  #@ for/end release in data.values.baseReleases:
  - #@ "update-" + release.name
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: relint-envs
    - get: cf-deployment-develop
    - get: cf-deployment-concourse-tasks
    #@ for/end release in data.values.baseReleases:
    - get: #@ release.name + "-release"
      params:
        tarball: false
    - get: stemcell
      trigger: true
      params:
        tarball: false
  - task: update-stemcell-manifest-section
    file: runtime-ci/tasks/update-stemcell-manifest-section/task.yml
    input_mapping:
      deployment-configuration: cf-deployment-develop
  - task: upload-updated-stemcell
    file: cf-deployment-concourse-tasks/bosh-upload-stemcells/task.yml
    input_mapping:
      bbl-state: relint-envs
      cf-deployment: updated-deployment-manifest
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      INFRASTRUCTURE: google
  - aggregate:
    #@ for/end release in data.values.baseReleases:
    - task: #@ "compile-release-" + release.name
      file: runtime-ci/tasks/compile-release-from-manifest/task.yml
      input_mapping:
        bbl-state: relint-envs
        manifest: updated-deployment-manifest
      output_mapping:
        exported-release: #@ "exported-release-" + release.name
      params:
        BBL_STATE_DIR: environments/test/greengrass/bbl-state
        RELEASE_NAME: #@ release.name
  #@ for/end release in data.values.baseReleases:
  - task: #@ "update-compiled-releases-ops-" + release.name
    file: runtime-ci/tasks/update-single-compiled-release/task.yml
    input_mapping:
      #@ if hasattr(release, "bootstrap"):
      original-compiled-releases-ops-file: cf-deployment-develop
      #@ else:
      original-compiled-releases-ops-file: updated-compiled-releases-ops-file
      #@ end
      release: #@ release.name + "-release"
      compiled-release-tarball: #@ "exported-release-" + release.name
      current-commit-message: commit-message
    params:
      RELEASE_NAME: #@ release.name
      #@ if hasattr(release, "bootstrap"):
      ORIGINAL_OPS_FILE_PATH: operations/use-compiled-releases.yml
      #@ else:
      ORIGINAL_OPS_FILE_PATH: use-compiled-releases.yml
      #@ end
      UPDATED_OPS_FILE_PATH: use-compiled-releases.yml
  - aggregate:
    #@ for/end release in data.values.baseReleases:
    - put: #@ release.name + "-release-gcs"
      params:
        file: #@ "exported-release-" + release.name + "/*.tgz"
        predefined_acl: publicRead
  - task: commit-generated-manifest-and-ops
    file: runtime-ci/tasks/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      ops-file: updated-compiled-releases-ops-file
      manifest: updated-deployment-manifest
    params:
      MANIFEST_NAME: cf-deployment.yml
      MANIFEST_DESTINATION: cf-deployment.yml
      OPS_FILE_NAME: use-compiled-releases.yml
      OPS_FILE_DESTINATION: operations/use-compiled-releases.yml
  - put: cf-deployment-develop
    params:
      rebase: true
      repository: updated-repo

- name: update-windows-2016-offline-releases
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: runtime-ci
    - get: relint-envs
    - get: cf-deployment-develop
    - get: cf-deployment-concourse-tasks
      params:
        tarball: false
    - get: windows2016fs-offline-release
      trigger: true
      params:
        tarball: false
    - get: windows2016-stemcell
  - task: update-windows-releases
    file: runtime-ci/tasks/update-single-opsfile-release/task.yml
    input_mapping:
      original-ops-file: cf-deployment-develop
      release: windows2016fs-offline-release
    params:
      RELEASE_NAME: windows2016fs
      ORIGINAL_OPS_FILE_PATH: operations/use-offline-windows2016fs.yml
      UPDATED_OPS_FILE_PATH: use-offline-windows2016fs.yml
  - task: commit-generated-manifest-and-ops
    file: runtime-ci/tasks/commit-generated-manifest/task.yml
    input_mapping:
      repo: cf-deployment-develop
      ops-file: updated-ops-file
      manifest: cf-deployment-develop
    params:
      OPS_FILE_DESTINATION: operations/use-offline-windows2016fs.yml
      OPS_FILE_NAME: use-offline-windows2016fs.yml
  - put: cf-deployment-develop
    params:
      rebase: true
      repository: updated-repo

- name: setup-infrastructure-compilation
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: cf-deployment-concourse-tasks
    - get: runtime-ci
    - get: relint-envs
  - task: setup-infrastructure
    file: cf-deployment-concourse-tasks/bbl-up/task.yml
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      BBL_CONFIG_DIR: environments/test/greengrass/bbl-config
      BBL_IAAS: gcp
      BBL_GCP_SERVICE_ACCOUNT_KEY: environments/test/greengrass/google_account_creds.json
      BBL_GCP_REGION: us-central1
      BBL_LB_CERT: ((greengrass_cf_lb_cert.certificate))
      BBL_LB_KEY: ((greengrass_cf_lb_cert.private_key))
      LB_DOMAIN: greengrass.cf-app.com
      BBL_ENV_NAME: greengrass-compile
    input_mapping:
      bbl-state: relint-envs
      bbl-config: relint-envs
    ensure:
      put: relint-envs
      params:
        repository: updated-bbl-state
        rebase: true
  - task: extend-cloud-config-for-credhub-dry-run
    file: runtime-ci/tasks/bosh-extend-cloud-config/task.yml
    input_mapping:
      ops-file: relint-envs
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      OPS_FILE_PATH: environments/test/greengrass/add-credhub-lb.yml

- name: destroy-infrastructure-compilation
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - aggregate:
    - get: relint-envs
    - get: runtime-ci
    - get: cf-deployment-concourse-tasks
  - task: guarantee-no-existing-cf-deployment
    file: cf-deployment-concourse-tasks/bosh-delete-deployment/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
  - task: destroy-infrastructure
    file: cf-deployment-concourse-tasks/bbl-destroy/task.yml
    input_mapping:
      bbl-state: relint-envs
    params:
      BBL_STATE_DIR: environments/test/greengrass/bbl-state
      BBL_GCP_SERVICE_ACCOUNT_KEY: environments/test/greengrass/google_account_creds.json
    ensure:
      put: relint-envs
      params:
        repository: updated-bbl-state
        rebase: true

- name: run-bosh-cleanup-compilation
  serial: true
  public: true
  build_logs_to_retain: 100
  plan:
  - timeout: 4h
    do:
    - aggregate:
      - get: cf-deployment-concourse-tasks
      - get: relint-envs
      - get: daily
        trigger: true
    - task: run-bosh-cleanup
      file: cf-deployment-concourse-tasks/bosh-cleanup/task.yml
      input_mapping:
        bbl-state: relint-envs
      params:
        BBL_STATE_DIR: environments/test/greengrass/bbl-state
